name: CI

on:
  push:
    branches: [master]
    
jobs:
  pipeline:
    runs-on: [windows-latest]
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@master
        
      - name: Build Solution
        run: dotnet build --configuration Release src
      
      - name: Run Tests
        run: dotnet test src
      
      - name: Create Package
        run: dotnet pack src/InstrumentedAdoNet --configuration Release 
      
      - uses: actions/setup-dotnet@master
        with:
            source-url: https://api.nuget.org
        env:
            NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      
      - name: Publish Package
        run: dotnet nuget push -s https://www.nuget.org/api/v2/package -k $NUGET_AUTH_TOKEN 'src\InstrumentedAdoNet\bin\Release\*.nupkg'
